# .github/workflows/firebase-hosting-push.yml

name: Deploy to Firebase Hosting on push

on:
  push:
    branches:
      - staging # Change this to any branch you use for testing or updates

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ARABA50MESSAGES }}
          channelId: live # Or use preview if you want
          projectId: araba50messages
